<?php

namespace imovel\Entity;

/**
 * ContratacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
