<?php

namespace imovel\Entity;

/**
 * EmailConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
