<?php

namespace imovel\Entity;

/**
 * InquilinoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InquilinoRepository extends \Doctrine\ORM\EntityRepository
{
}
