<?php

namespace imovel\Entity;

/**
 * ProprietarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProprietarioRepository extends \Doctrine\ORM\EntityRepository
{
}
